### ISSUE TITLE
v2.1: Umbrella header for module 'JLRoutes' does not include header 'JLRRoute___________.h'

### ISSUE THREAD

**Issue by Nonnus** [joeldev/JLRoutes#105]
After updating JLRoutes from version 2.0.5 to 2.1 we get several warnings: 
"Umbrella header for module 'JLRoutes' does not include header 'JLRRouteRequest.h'"
"Umbrella header for module 'JLRoutes' does not include header 'JLRRouteResponse.h'"
"Umbrella header for module 'JLRoutes' does not include header 'JLRRouteHandler.h'"
"Umbrella header for module 'JLRoutes' does not include header 'JLRRouteDefinition.h'"

**Comment by joeldev** [comment]
Fixed by #102, will make a new release soon.
