### ISSUE TITLE
xcode warnings when using latest 2.1 release

### ISSUE THREAD

**Issue by Nonnus** [joeldev/JLRoutes#110]
After updating from release 2.0.6 to 2.1 using Carthage my project has several JLRoutes related warnings:
<img width="260" alt="screen shot 2018-08-03 at 04 12 18" src="https://user-images.githubusercontent.com/54864/43620603-e1d2af06-96d3-11e8-87ec-02a5d2cea81d.png">

Xcode 9.4.1 / Swift 4.1.2
macOS 10.13.6

**Comment by punty** [comment]
@joeldev can we get a new release with this fix (from master)?

**Comment by min** [comment]
@Nonnus give https://github.com/min/Routes a shot

**Comment by lickel** [comment]
This issue should be resolved on master
