### ISSUE TITLE
Add more view controller awareness

### ISSUE THREAD

**Issue by joeldev** [joeldev/JLRoutes#39]
One of the things that's still kind of unclear how to implement is the common pattern of handling a route by showing a new view controller (such as to view a user profile). A lot can be done to improve on that.

**Comment by orta** [comment]
I wrote a bit about how we do this in Artsy apps: http://artsy.github.io/blog/2015/08/18/Cocoa-Architecture:-Switchboard-Pattern/

One pattern for auto-connecting VCs is in [Routable](https://cocoapods.org/pods/Routable).

**Comment by timbroder** [comment]
Updated link to @orta's post above: http://artsy.github.io/blog/2015/08/19/Cocoa-Architecture-Switchboard-Pattern/
