### ISSUE TITLE
Adding a route with nonzero priority fails if there are no routes yet

### ISSUE THREAD

**Issue by cdzombak** [joeldev/JLRoutes#46]
Given a `JLRoutes` instance `router`, the following lines of code result in _no routes_ being added to the router:

```swift
router.addRoute("/:entityType/id/:id", priority: 20, handler: handler)
router.addRoute("/:entityType/open-modal/:id", priority: 10, handler: handler)
router.addRoute("/:entityType/:id", priority: 1, handler: handler)
```

This problem occurs in `-addRoute:priority:handler:`, specifically:

```objc
	if (priority == 0) {
		[self.routes addObject:route];
	} else {
		NSArray *existingRoutes = self.routes;
		NSUInteger index = 0;
		for (_JLRoute *existingRoute in existingRoutes) {
			if (existingRoute.priority < priority) {
				[self.routes insertObject:route atIndex:index];
				break;
			}
			index++;
		}
	}
```

Seeing that we're adding a route with a nonzero priority, we enter the `else` part of that logic, which is supposed to iterate over existing routes and insert the new route just ahead of the first route of lower priority. But since this is the first route we're trying to add there's nothing in `existingRoutes`, so we never enter the `for` loop and the route is never added.

This could be fixed by changing the conditional to read `if (priority == 0 || self.routes.count == 0)`.

**Comment by ivany4** [comment]
+1. Is it gonna be fixed in the near future?
