### ISSUE TITLE
Ability to query routes

### ISSUE THREAD

**Issue by ZevEisenberg** [joeldev/JLRoutes#49]
It would be nice if you could query JLRoutes for all the currently registered routes, and then generate, for example, a testing UI that provides easy links to all the routes in the app.

**Comment by ZevEisenberg** [comment]
Paging @mgorbach, who was interested in this.

**Comment by joeldev** [comment]
This is a brilliant idea.

**Comment by clooth** [comment]
Could someone open up this feature idea a bit more, so I can get a clear idea of what functionality is wanted?

**Comment by ZevEisenberg** [comment]
I was thinking all the route registrations would be exposed in an array. You could then list them somewhere like [RZDebugMenu](https://github.com/Raizlabs/RZDebugMenu) or similar. When you tap a route, if it has `*` matchers, they would prompt for text input (and be prepopulated with the last input).

I’m not sure how much of this would be built in to JLRoutes and how much would be up to the host app. I was thinking JLRoutes would just expose the route registrations in an easily consumable format.

**Comment by hpsoar** [comment]
It would be nice to have a query feature.

Besides, I think it would be better if _JLRoute creation process is separated from JLRoutes, and expose _JLRoute to public.

So that users can encapsulate a route logic in a _JLRoute subclass, then they can create, add, query, test, perform _JLRoute as they wish.

**Comment by MarshalGeazipp** [comment]
It would be great to have this feature, I would use it for sure! 
Is anybody working on it?

**Comment by joeldev** [comment]
Two new methods I just pushed:
```objc
/// All registered routes, keyed by scheme
+ (NSDictionary <NSString *, JLRRouteDefinition *> *)allRoutes;

/// Return all registered routes in the receiving scheme namespace.
- (NSArray <JLRRouteDefinition *> *)routes;
```

Sorry that took so long.

**Comment by MarshalGeazipp** [comment]
Works great. 
Thank you very much!
