### ISSUE TITLE
JLRoutes.m:line 112 -  Value stored into 'NSMutableDictionary' cannot be nil

### ISSUE THREAD

**Issue by BigSauce** [joeldev/JLRoutes#51]
Running a code analysis on a project of mine which includes JLRoutes, I noticed that JLRoutes attempts to add an object which can potentially be nil to an NSMutableDictionary.

![image](https://cloud.githubusercontent.com/assets/1718470/7454349/d61f92b8-f240-11e4-91ff-c36fb3f292ff.png)

**Comment by joeldev** [comment]
Hmm, this was fixed in January in commit 4022a8c369f8.

Are you using the latest version? (1.5.2)
