### ISSUE TITLE
iOS 9 compatability/readiness?

### ISSUE THREAD

**Issue by khappucino-nordstrom** [joeldev/JLRoutes#53]
Are there any known issues with iOS9?

**Comment by joeldev** [comment]
We haven't seen any problems yet, but we also haven't done extensive testing. If anyone else has seen a problem, feel free to chime in now... (I'll leave this issue open for the moment).

**Comment by orta** [comment]
No problems with [artsy/eigen](https://github.com/artsy/eigen/)

**Comment by joeldev** [comment]
Closing this issue now. Feel free to open a new one if you find a problem with iOS 9 compatibility.
