### ISSUE TITLE
Route aliasing

### ISSUE THREAD

**Issue by philipengberg** [joeldev/JLRoutes#54]
In order to gracefully handle backwards compatibility, it would be great if you could add a route alias during the transitioning period between route changes.

So if in an old version the profile deeplinking route was `/profile/:username` and in a later version is `/user/:username`, one would have to have to support both routes in the transitioning period until the old route can be deprecated. This means that you would have to have the exact same handler for two different routes:

```objective-c
[JLRoutes addRoute:@"/profile/:username" handler:^BOOL(NSDictionary *parameters) {
    // Show profile
    return YES;
}];

[JLRoutes addRoute:@"/user/:username" handler:^BOOL(NSDictionary *parameters) {
    // Show profile
    return YES;
}];
```

Instead it would be nice to be able to do something like:

```objective-c
[JLRoutes addAlias:@"/profile/:username" forRoute:@"/user/:username"];
```
resulting in the `/user/:username` handler being invoked for the `/profile/:username` route.

I know that one could just factor this functionality out into an external method, but it would be a much appreciated feature nonetheless.

**Comment by ylovern** [comment]
as you mean ,I think use array like 
```
[JLRoutes addRoute:@[@"/profile/:username",@"/user/:username"] handler:^BOOL(NSDictionary *parameters) {
    // Show profile
    return YES;
}];
```
is better.(if JLRoutes support 0.0)

**Comment by philipengberg** [comment]
Good point

**Comment by philipengberg** [comment]
https://github.com/joeldev/JLRoutes/pull/55

**Comment by joeldev** [comment]
#55 has been merged, closing this issue now. Thanks again!
