### ISSUE TITLE
problem for one more "=" cases 

### ISSUE THREAD

**Issue by alpersenyurt** [joeldev/JLRoutes#58]
If my url is like   

app://webview?url=http://images.domain.net/assets/gif/domain/push.html?kod=213"

in JLRoutes_URLParameterDictionary method  			
NSString *paramValue = pair.count == 2 ? pair[1] : @"";
 for in this case ,my pair count 3  so
paramValue returns @"" but I need paramValue http://images.domain.net/assets/gif/domain/push.html?kod=213

**Comment by joeldev** [comment]
This is a duplicate of #43
