### ISSUE TITLE
Don't be shy about supporting carthage

### ISSUE THREAD

**Issue by maximveksler** [joeldev/JLRoutes#62]
Hey guys, 

Just writing to let you know that carthage works great with your repo setup, so it's a quick win to let people know they can use it. 

All you have to do is add

`github "joeldev/JLRoutes"` to your `Cartfile` and bam, now this happens:

```
➜  finder-ios git:(master) ✗ carthage update
*** Cloning JLRoutes
*** Checking out JLRoutes at "1.5.5"
*** Building scheme "JLRoutes-iOS" in JLRoutes.xcodeproj
```

**Comment by joeldev** [comment]
Good call! I've updated the readme to reflect Carthage support. Thanks!
