### ISSUE TITLE
Wildcard only works at the end of a URL

### ISSUE THREAD

**Issue by tyten** [joeldev/JLRoutes#66]
It seems the wildcard only works if it is at the end of a URL. Example: *.imgur.com routes everything through it regardless of what comes after.

**Comment by Zeeker** [comment]
The documentation states explicitly that this is the case:

> JLRoutes supports setting up routes that will match an arbitrary number of path components at the end of the routed URL.

[Link](https://github.com/joeldev/JLRoutes#scheme-namespaces)

**Comment by joeldev** [comment]
@Zeeker Fair point. Sorry @tyten, going to close this. I don't think adding support is something I'm considering.
