### ISSUE TITLE
Unsupported special characters

### ISSUE THREAD

**Issue by ou2s** [joeldev/JLRoutes#70]
I have this url:
`example://query?test=sp%E8cial`

However JLRoutes is unable to parse the `test` parameter because of the "%E8" character. 

Is there any way to support special characters?

To workaround this issue, I had to modify the `JLRoutes_URLDecodedString` method because it is returning NULL.

**Comment by ou2s** [comment]
In order for JLRoutes to work with those special characters I had to change the `JLRoutes_URLDecodedString`  method replacing:
`return [input stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding];`
by:
`return [input stringByReplacingPercentEscapesUsingEncoding:NSISOLatin1StringEncoding];`

**Comment by joeldev** [comment]
Glad to hear this works after all! Feel free to file another issue if this pops up again.
