### ISSUE TITLE
Ability to register regex url pattern

### ISSUE THREAD

**Issue by tennysondy** [joeldev/JLRoutes#80]
Could JLRoutes add the regex match? Sometimes I want to register regex pattern like  ^.*.test.com/.* . Then I can handle the specific url like m.test.com, h5.test.com etc .

**Comment by joeldev** [comment]
I have no plans to support this for now. However, you could subclass JLRRouteDefinition to add your own support for this in your app if you want. I may look into adding a built-in route class that supports this at some point.
