### ISSUE TITLE
Possible mutation of self.routes during routeURL if route is added at the same time

### ISSUE THREAD

**Issue by bcriscuolo** [joeldev/JLRoutes#81]
This one gets me from time to time, as the process of routing a URL ends up adding a route elsewhere, and the outcome is always "fun".

`routeURL:withParameters:executeRouteBlock:` uses fast enumeration of `self.routes` to match for a valid route handler.

However, while this enumeration is happening, `register` or `remove` methods may be called which will modify the mutable array of self.routes.

I suggest that in `routeURL:withParameters:executeRouteBlock:` you first copy self.routes to an immutable NSArray and use that to enumerate the routes contained.

You'd be protected against the dreaded `Collection <__NSArrayM: 0x17405dc70> was mutated while being enumerated.` error.

Thank you. Keep up the good work,

Brian M. Criscuolo
warmwinds software

**Comment by bcriscuolo** [comment]
There are other places where self.routes is enumerated in the code; any place this is happening is ripe for having a local copy of the array to be used for the enumeration.

**Comment by joeldev** [comment]
Good find! I can't believe I missed that.
