### ISSUE TITLE
Crash on iOS 7.x

### ISSUE THREAD

**Issue by iShawnWang** [joeldev/JLRoutes#83]
`JLRRouteRequest` Line 81
`@property (nullable, copy) NSArray<NSURLQueryItem *> *queryItems NS_AVAILABLE(10_10, 8_0);`

Cause Crash on device with iOS 7.x

**Comment by joeldev** [comment]
Ah, sorry about that. Unfortunately, I am not interesting in maintaining a 7.x compatible-version of the latest code, given how much code is saved by using `queryItems`.  I recommend continuing to use JLRoutes version 1.6.4 (tagged in git and also available via cocoapods) until you no longer have to support 7.x. I'll update the project to explicitly require 8.0. Thanks!
