### ISSUE TITLE
Add pre-compiled framework to the release for Carthage

### ISSUE THREAD

**Issue by veeamd** [joeldev/JLRoutes#85]
Hi,
I think a lot of JLRoutes projects are using CircleCI, or similar to build builds
If you can attach the pre-compiled framework: JLRoutes.framework.zip to the release, this will save tons of CircleCI building time.
Thanks,
Wei

**Comment by joeldev** [comment]
Sorry, I don't think this is worth doing at this time. JLRoutes is a tiny framework.
