### ISSUE TITLE
JLRoutes 2.0.2 doesn't support multiple hosts

### ISSUE THREAD

**Issue by runmad** [joeldev/JLRoutes#88]
In `JLRRouteRequest`:
```obj-c
NSURLComponents *components = [NSURLComponents componentsWithString:[self.URL absoluteString]];
if (components.host.length > 0 && ![components.host isEqualToString:@"localhost"]) {
    // convert the host to "/" so that the host is considered a path component
    NSString *host = [components.percentEncodedHost copy];
    components.host = @"/";
    components.percentEncodedPath = [host stringByAppendingPathComponent:(components.percentEncodedPath ?: @"")];
}
```

This doesn't allow for a support of a variety of hosts. For example, I've tested with:

`https://www.mydomain.com/path/3` and `https://www.mydomain-test.com/path/3` and these resolve to paths that are `www.mydomain.com/path/3` and `mydomain-test.com/path/3`, which means if I add a route for `/path/:pathid` nothing matches, since it's trying to match on a path that includes the domain as well.

I haven't seen a workaround for this, but needing to support multiple hosts, this is a breaking change after updating from `1.6.3`.

I don't want to submit a PR in case there's a reason for this change, so would like to know why the path is overridden to include the host?

**Comment by joeldev** [comment]
Can I see an example of what your `addRoute` call might look like for these? Just trying to full wrap my head around what you're trying to do. I think I might just add a way to configure this parsing behavior, as it seems to be one way or the other depending on the product and needs.

**Comment by runmad** [comment]
Hi @joeldev, thanks for replying.

Here's few examples:

`[[JLRoutes globalRoutes] addRoute:@"/sign_in" handler:^BOOL(NSDictionary *parameters) {}];`
`[[JLRoutes globalRoutes] addRoute:@"/market/:marketId" handler:^BOOL(NSDictionary *parameters) {}];`

And calling `[JLRoutes routeURL:url];` or `[[JLRoutes globalRoutes] routeURL:url];` doesn't work - it fails in the part of the method above as it's adding the host to the path as mentioned in my original post.

We have several domains that the app can handle, so all we care about is the path component of the URL: `/sign_in`, `/market/:marketId`, etc. not `www.domain.com/sign_in`.

Previously we used:

`[JLRoutes addRoute:@"/sign_in" handler:^BOOL(NSDictionary *parameters) {}];` which has been deprecated and `[JLRoutes routeURL:url];` and this worked perfectly (in `1.6.3`)

Worth mentioning, it works fine if the URL is something like `myapp://sign_in`.

**Comment by joeldev** [comment]
Ah, I see why this broke between `1.6.3` and now. This is what the code used to look like:
```objc
if ([URL.host rangeOfString:@"."].location == NSNotFound && ![URL.host isEqualToString:@"localhost"]) {
    // For backward compatibility, handle scheme://path/to/resource as if path was part of the path
    pathComponents = [@[URL.host] arrayByAddingObjectsFromArray:pathComponents];
}
```

So it appears to have been taking into account if there was a period in the host, but that was dropped. I don't think that was intentional. Working on a fix and tests now.

**Comment by runmad** [comment]
Awesome, thanks so much!

**Comment by joeldev** [comment]
Just pushed version 2.0.3 with this fix included. Feel free to file more issues if anything comes up!

**Comment by runmad** [comment]
Works perfectly, thanks very much for the speedy release!
