### ISSUE TITLE
JLRoutes 2.0.3 doesn't support host as parameter

### ISSUE THREAD

**Issue by danielebogo** [joeldev/JLRoutes#89]
Is it possible to switch between the possibility to keep the host as parameter?
This because this minor release affects all the app are using it with this behaviour.
I can suggest a pull request if you want.

**Comment by joeldev** [comment]
Ugh, I was wondering if anyone was depending on this. I'll have to add an option to control this behavior. The change to always use the host as a path component was not intentional and happened while the 2.0 rewrite was happening.

Can you give me an example of your `addRoute:handler:` call and a URL that was working before but isn't? Just want to make sure the change I make fixes your issue.

**Comment by joeldev** [comment]
I pushed 1af2a1ccc4a17a87757ecb10bf1d78f8ce738e45 which likely fixes it, but I'm going to keep this open until you confirm your precise use-case and I can test it out. After we do that, I'll push another point release.

**Comment by danielebogo** [comment]
Well we use this structure:
```
[ "https": [ "www.my_host_name.com/path/:placeholder/*", "...", "..." ] ]
```
Every url contains the complete path (host included). So the match doesn't work anymore cause the path elements doesn't contain the host, and the "canRoute" method returns always no.
Let me try this commit and i'll let you know.

**Comment by joeldev** [comment]
@danielebogo: okay, based on that comment I believe that this commit will fix your issue. Did you get a chance to try it? I'd like to release a new point update with the fix.

**Comment by danielebogo** [comment]
@joeldev yes i've tried on a little side project i've and it works. Tomorrow morning i'll test it again with another one. But i'm sure it's fixed right now.

**Comment by joeldev** [comment]
Great! I'll push a release (2.0.4). Thanks for the help!

**Comment by danielebogo** [comment]
@joeldev thanks a lot! I tested it on my big project i.m working on and it works!
