### ISSUE TITLE
Could not find a matching route

### ISSUE THREAD

**Issue by sucrewar** [joeldev/JLRoutes#92]
Hello,
I have a register route but jlroutes always tell could not find a matching route.
There is a print of JLRoutes.allRoutes(), with the route register:

> ["JLRoutesGlobalRoutesScheme": [<JLRRouteDefinition 0x61000005f560> - home (priority: 0), <JLRRouteDefinition 0x61000005f4a0> - login (priority: 0), <JLRRouteDefinition 0x61000005f620> - profile (priority: 0), <JLRRouteDefinition 0x61000005f7d0> - invite (priority: 0), <JLRRouteDefinition 0x61000005f830> - settings (priority: 0), <JLRRouteDefinition 0x61000005f920> - trending (priority: 0), <JLRRouteDefinition 0x61000005f9e0> - feedback (priority: 0), <JLRRouteDefinition 0x61000005fa70> - cloud (priority: 0), <JLRRouteDefinition 0x61000005fb30> - contentDetail (priority: 0)]]

And the error return by JLRoutes:
> 2017-07-17 12:33:17.697 uscope[55891:9500137] [JLRoutes]: Trying to route URL contentDetail
> 2017-07-17 12:33:17.697 uscope[55891:9500137] [JLRoutes]: Could not find a matching route

There is my register routes func:
```
    static func setupRoutes () {
        let routes = JLRoutes.global()
        JLRoutes.setVerboseLoggingEnabled(true)
        
        routes.addRoute("home") { (parameters) -> Bool in
            return self.handleHomeView(parameters: parameters)
        }
        
        routes.addRoute("login") { (parameters) -> Bool in
            return self.handleLoginView(parameters: parameters)
        }
        
        routes.addRoute("profile") { (parameters) -> Bool in
            return self.handleProfileView(parameters: parameters)
        }
        
        routes.addRoute("invite") { (parameters) -> Bool in
            return self.handleInviteView(parameters: parameters)
        }
        
        routes.addRoute("settings") { (parameters) -> Bool in
            return self.handleSettingsView(parameters: parameters)
        }
        
        routes.addRoute("trending") { (parameters) -> Bool in
            return self.handleTrendingView(parameters: parameters)
        }
        
        routes.addRoute("feedback") { (parameters) -> Bool in
            return self.handleFeedbackView(parameters: parameters)
        }
        
        routes.addRoute("cloud") { (parameters) -> Bool in
            return self.handleCloudView(parameters: parameters)
        }
        
        routes.addRoute("contentDetail") { (parameters) -> Bool in
            return self.handleAssignmentDetail(parameters: parameters)
        }

        print(JLRoutes.allRoutes())
    }
```

**Comment by joeldev** [comment]
Hmm, interestingly enough I am not able to reproduce this. The following example works for me:

```objc
[[JLRoutes globalRoutes] addRoute:@"foo" handler:^BOOL(NSDictionary<NSString *,id> * _Nonnull parameters) {
    // handled
    NSLog(@"handled");
}];

[JLRoutes routeURL:[NSURL URLWithString:@"foo"] withParameters:nil];
```

What does your code look like to route the URL, and what does the code look like to create the URL? Do any of your routes work?

**Comment by sucrewar** [comment]
Hello,
Finally fix this issue. the error has been caused by JLRoutes().routeURL() instead JLRoutes.routeURL().
You can close the issue.
Thanks :)

**Comment by joeldev** [comment]
Ahh, that'll do it, thanks for following up!
