### ISSUE TITLE
JLRoutes does not handle addRoute when open(url, options: [:]) is called

### ISSUE THREAD

**Issue by avshiyanov** [joeldev/JLRoutes#93]
Starting from iOS10 when I call UIApplication.shared.open(url, options: [:]) addRoute does not work (it simply opens Safari),
it works only with deprecated method UIApplication.shared.openURL(url)

**Comment by joeldev** [comment]
If you specifically want JLRoutes to handle it, you can just replace that line with `JLRoutes.routeURL(url)`. I'm not sure what changed in iOS exactly, but there's not really a reason to pass it indirectly. I'll have to do some testing of this and will probably update the README to reflect this.
